### ISSUE TITLE
Fifo scheduler not working?

### ISSUE THREAD

**Issue by fraPace** [DistributedSystemsGroup/zoe#42]
When checking the status of an application submitted to Zoe, I get the following status:

Execution scheduler20 (ID: 92013)
Status: cleaning up
Time submit: 2016-10-31 12:53:27.329355
Time start: not yet
Time end: not yet
Application name: cluster-scheduler-simulator
Service cluster-scheduler-simulator0 (ID: 95494)
 - zoe status: error
 - docker status: undefined
 - error: Not enough free resources to satisfy reservation request

Shouldn't be the application in scheduling status instead of "cleaning up"?

**Comment by dvenza** [comment]
The execution was not properly cleaned up, should be fixed now.
