### ISSUE TITLE
Configuration File parser

### ISSUE THREAD

**Issue by fraPace** [DistributedSystemsGroup/zoe#47]
I found a small problem when parsing the configuration file for Zoe.

When the value for a key is left blank, the parser will take the "=" as value.

This means that:
`overlay-network-name = `
is translated into
`overlay-network-name:=`
instead of
`overlay-network-name:`

When removing the "=" from the configuration file, the value for that key is `True`

**Comment by dvenza** [comment]
According to the `configargparse` parser documentation this is the expected behavior. I concur that it is a bit strange, but we will not fix it.
