### ISSUE TITLE
link delete don't appear anymore on the user webpage

### ISSUE THREAD

**Issue by thpiotrowski** [DistributedSystemsGroup/zoe#57]
Hello,
I just installed the latest version and the link "delete" don't appear anymore on the user webpage. When you click "restart" a new execution appears. 
![capture_zoe](https://user-images.githubusercontent.com/31432995/30378842-d748ae2a-9894-11e7-9736-cd5fc18bc481.GIF)

Brgds,
Thomas

**Comment by dvenza** [comment]
Tomorrow I will merge the branch devel/zapp-shop that contains a completely redesigned UI. The "delete" link will be available only for administrators. The idea is that past executions contain useful staistical data/logs and should not be deleted in general.

**Comment by dvenza** [comment]
I merged the UI branch. Executions can be deleted via the command line: `zoe-admin.py exec-rm <exec_id>`.

**Comment by thpiotrowski** [comment]
OK, I didn't have time to test it but I will next week and keep you posted, thanks.

**Comment by thpiotrowski** [comment]
Hello, the rm works fine and the new UI is a great improvment, thanks !
