### ISSUE TITLE
Additional volumes not mounted correctly

### ISSUE THREAD

**Issue by thpiotrowski** [DistributedSystemsGroup/zoe#58]
There is an error in the file zoe_lib/state/service.py
Line 150:
self.volumes = [VolumeDescriptionHostPath(v['path'], v['name'], v['read_only']) for v in self.description['volumes']]
should be
self.volumes = [VolumeDescriptionHostPath(v['name'], v['path'], v['read_only']) for v in self.description['volumes']]

**Comment by dvenza** [comment]
Good catch! I'll fix it shortly. Thanks
