### ISSUE TITLE
ZApp Shop

### ISSUE THREAD

**Issue by fraPace** [DistributedSystemsGroup/zoe#59]
I found couple of minor problems inside the ZApp shops:

1. Distributed PySpark Notebook is not working. The Spark Master crashes right away and make the app unusable. Suggestion: increase the memory.

2. Spark Submit might have the same problem of 1.

In addition it would be great to have something to export the ZApp Description of those applications, so that the user can quickly modify some parameters (e.g., the resources requirement) and launch a custom one.

**Comment by dvenza** [comment]
The Spark Master has already 2GB of RAM and is starting correctly in both ZApps.
