### ISSUE TITLE
ldap auth

### ISSUE THREAD

**Issue by thpiotrowski** [DistributedSystemsGroup/zoe#60]
Hello,
ldap authentification is not working as we would like. The ldap users are not allowed to browse the ldap directory. Could you  add in zoe.conf an ldap_tech_user and its password and the bind option which will the one who will browse the ldap directory. 
The field to get the group name is not gidNumber but something else so we need to have this in the zoe.conf. When you check the ldap_gid and expect an integer our directory gives us a string.
What we did to make it works is we got rid of the type=int for ldap_*_gid in zoe_lib/config.py. Then we modified the zoe_api/auth/ldap.py like this:

    def auth(self, username, password):
        """Authenticate the user or raise an exception."""
        search_filter = "cn=" + username
        uid = None
        role = 'guest'
        user_tech = "user_tech"
        bind_passwd = "pwd_tech"
        bind_user = 'cn=' + username + "," + self.base_dn
        bind_user_tech = 'cn=' + user_tech + ",ou=yyyyy,o=xxxxx"
        auth_ok = True
        try:
            self.connection.bind_s(bind_user, password)
        except ldap.LDAPError as ex:
            auth_ok = False
            log.warning("Auth KO")
            if ex.args[0]['desc'] == 'Invalid credentials':
                raise zoe_api.exceptions.ZoeAuthException('Unknown user or wrong password.')
            else:
                log.exception("LDAP exception")
                zoe_api.exceptions.ZoeAuthException('LDAP error.')
       if auth_ok:
          log.warning("Auth OK")
          try:
              self.connection.bind_s(bind_user_tech, bind_passwd)
              result = self.connection.search_s(self.base_dn, ldap.SCOPE_SUBTREE, search_filter)
              if len(result) == 0:
                  raise zoe_api.exceptions.ZoeAuthException('Unknown user or wrong password.')
              user_dict = result[0][1]
              uid = username
              gid_numbers = [str(x) for x in user_dict['XXXXXXXXXXXXX']]
              if any(get_conf().ldap_admin_gid in s for s in gid_numbers):
                  role = 'admin'
              elif get_conf().ldap_user_gid in gid_numbers:
                  role = 'user'
              elif get_conf().ldap_guest_gid in gid_numbers:
                  role = 'guest'
              else:
                  role = 'guest'
                  log.warning('User {} has an unknown group ID ({}), using guest role'.format(username, result[0][1]['XXXXXXXXXXXXX']))
          except ldap.LDAPError as ex:
              log.warning("LDAP ERROR AFTER AUTH")
              if ex.args[0]['desc'] == 'Invalid credentials':
                  raise zoe_api.exceptions.ZoeAuthException('Unknown user or wrong password.')
              else:
                  log.exception("LDAP exception")
                  zoe_api.exceptions.ZoeAuthException('LDAP error.')
          finally:
              self.connection.unbind_s()
        return uid, role

Brgds,
Thomas

**Comment by dvenza** [comment]
Please test and let me know if the changes implemented work for you,

**Comment by thpiotrowski** [comment]
Hello,
Thank you it is working fine we just had to make a small change because our ldap directory doesn't allow to make a search with userid. 
Brgds,
Thomas
