### ISSUE TITLE
Mixture of node_ip and node.name in kubernetes api_client

### ISSUE THREAD

**Issue by djohn156** [DistributedSystemsGroup/zoe#62]
In the function `info` in file `zoe_master/backends/kubernetes/api_client.py`, the keys of the dictionary `node_dict` is built using `node.name`, but later referenced via `node_ip`. These may not necessarily be the same (e.g. node.name might return a domain name) leading to a KeyError in line 436.

Potential solution:
Building the dictionary explicitely using IPs, e.g. by Python's socket module via
`node_dict[str(socket.gethostbyname(node.name))] = nss` in line 416

**Comment by dvenza** [comment]
Good catch, thanks!
