### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by thpiotrowski** [DistributedSystemsGroup/zoe#67]
Hello,
When docker is stopped on a node and we try to terminate an execution with containers running on the stopped node then zoe_master crash. Please find the errors listed in the master log file below.
Best regards,
Thomas

> 2018-01-19 13:50:15,811 INFO synchro_cn03->zoe_master.backends.docker.threads: Node cn03 is offline
> 2018-01-19 13:50:23,483 ERROR MainThread->main: Fatal error in API loop
> Traceback (most recent call last):
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
>     raise err
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
>     chunked=chunked)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
>     self._validate_conn(conn)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
>     conn.connect()
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
>     conn = self._new_conn()
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3048853c18>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
>     timeout=timeout
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xx.yy.zz.tt', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3048853c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/api/client.py", line 168, in _retrieve_server_version
>     return self.version(api_version=False)["ApiVersion"]
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/api/daemon.py", line 177, in version
>     return self._result(self._get(url), json=True)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/utils/decorators.py", line 46, in inner
>     return f(self, *args, **kwargs)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/api/client.py", line 191, in _get
>     return self.get(url, **self._set_request_timeout(kwargs))
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
>     return self.request('GET', url, **kwargs)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
>     r = adapter.send(request, **kwargs)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xx.yy.zz.tt', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3048853c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/zoe/zoe_master/backends/docker/api_client.py", line 60, in __init__
>     self.cli = docker.DockerClient(base_url=docker_config.address, version="auto", tls=tls)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/client.py", line 38, in __init__
>     self.api = APIClient(*args, **kwargs)
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/api/client.py", line 149, in __init__
>     self._version = self._retrieve_server_version()
>   File "/tech/local/anaconda/3/lib/python3.5/site-packages/docker/api/client.py", line 176, in _retrieve_server_version
>     'Error while fetching server API version: {0}'.format(e)
> docker.errors.DockerException: Error while fetching server API version: HTTPSConnectionPool(host='xx.yy.zz.tt', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3048853c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/zoe/zoe_master/entrypoint.py", line 90, in main
>     api_server.loop()
>   File "/app/zoe/zoe_master/master_api.py", line 79, in loop
>     zoe_master.preprocessing.execution_terminate(self.scheduler, execution)
>   File "/app/zoe/zoe_master/preprocessing.py", line 90, in execution_terminate
>     terminate_execution(execution)
>   File "/app/zoe/zoe_master/backends/interface.py", line 183, in terminate_execution
>     terminate_service(service)
>   File "/app/zoe/zoe_master/backends/interface.py", line 165, in terminate_service
>     backend.terminate_service(service)
>   File "/app/zoe/zoe_master/backends/docker/backend.py", line 80, in terminate_service
>     engine = DockerClient(conf)
>   File "/app/zoe/zoe_master/backends/docker/api_client.py", line 62, in __init__
>     raise ZoeException("Cannot connect to Docker host {} at address {}: {}".format(docker_config.name, docker_config.address, str(e)))

**Comment by dvenza** [comment]
I saw this bug happening on our systems too and implemented a fix. Please check the new code at:
https://github.com/DistributedSystemsGroup/zoe/blob/a4fa73cbb1c77b30f43a783cb8abbdbf3e0b0f89/zoe_master/backends/docker/api_client.py#L198

It should catch the exception and also be faster when terminating containers.

**Comment by thpiotrowski** [comment]
The test is successfull zoe_master is not crashing anymore but still have some traceback
