### ISSUE TITLE
Zapp not starting when 1st connection to ZOE

### ISSUE THREAD

**Issue by thpiotrowski** [DistributedSystemsGroup/zoe#68]
Hello,
When you connect to ZOE for the 1st time (LDAP) and you launch a Zapp it won't start with this message:

> 2018-01-29 10:28:01,949 ERROR scheduler->zoe_master.backends.interface: Fatal error trying to start service 6 of execution 7: 500 Server Error: Internal Server Error ("error while creating mount source path '/path_wrkspace/userid': chown /path_wrkspace/userid: operation not permitted")

You just have to restart the Zapp and it will work. 

Regards,
Thomas

**Comment by dvenza** [comment]
I could never reproduce this issue, but it should be fixed with the new user management system being implemented.
