### ISSUE TITLE
Specify network to use in Zapp json

### ISSUE THREAD

**Issue by thpiotrowski** [DistributedSystemsGroup/zoe#74]
Hello,

We have a Zapp which is a jupyter standalone submitting spark application to an Hadoop cluster.Due to the ports configuration of the driver we didn't manage to make it work when the Zapp is not in the "host" network because on the "zoe" network the spark master (yarn) of the Hadoop cluster can't reach the driver.
Would be possible in the Zapp json to specify the network to use ?

Best regards,
Thomas

**Comment by dvenza** [comment]
Hello,

I implemented the network choice at the service level (each service can have a different network). If the value is not set, the network name will be taken from the configuration file (as in the current version).

The changes are simple and you can see them in this commit: feb01ba9afabfb0bb727ab6d0ba5d8e59ff2ae28

I modified only the DockerEngine implementation. Kubernetes does not have the same concept of networks and we will need to study how to translate it in that environment.

Let me know if this works for you.

**Comment by thpiotrowski** [comment]
Hello,
Great, thanks I'll test it asap.
Best regards,
Thomas

**Comment by thpiotrowski** [comment]
Hello, Sorry for this late answer, it is working like a charm, thanks !
